language: python
python:
  - "2.7"
  - "3.6"
addons:
  chrome: stable
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - export PATH=$TRAVIS_BUILD_DIR:$PATH
install: pip install selenium
script:
  - python setup.py install
  - python ./tests/tests.py  # Tests via setuptools run too long and hang too often on Travis
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "3.6"
notifications:
  email: false
